from pydantic import BaseModel, Field
from typing import Dict, List, Optional


# An AI conversation is just a list of messages. This class standardises what a single message looks like.
class GatewayMessage(BaseModel):
    role: str = Field(..., description="e.g., 'user' or 'model'")
    content: str

# This model defines what your incoming user requests must look like, regardless of which AI backend they want to target.
class GatewayRequest(BaseModel):
    model: str = Field(..., description="The specific model ID")
    messages: List[GatewayMessage]
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = None

class GatewayResponse(BaseModel):
    content: str = Field(..., description="The text generated by the AI")
    model: str = Field(..., description="The model that actually responded")
    usage: Dict[str, int] = Field(
        default_factory=dict, 
        description="Token usage tracking: {'prompt_tokens': X, 'completion_tokens': Y}"
    )
    # usage: A dictionary that tracks cost and consumption data (e.g., {"prompt_tokens": 12, "completion_tokens": 24}). By standardising these keys, you can build a unified analytics or billing feature later.