from pydantic import BaseModel, Field
from typing import Dict, List, Optional


# An AI conversation is just a list of messages. This class standardises what a single message looks like.
class GatewayMessage(BaseModel):
    role: str = Field(..., description="e.g., 'user' or 'model'")
    content: str
'''role: Identifies who said the message. It will typically be "user" (the human) or "assistant"/"model" (the AI response).content: The actual text string of the message (e.g., "What is the capital of France?").'''



# This model defines what your incoming user requests must look like, regardless of which AI backend they want to target.
class GatewayRequest(BaseModel):
    model: str = Field(..., description="The specific model ID, e.g., 'gemini-1.5-flash'")
    messages: List[GatewayMessage]
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = None

    '''messages: A list of the GatewayMessage objects we defined above, representing the chat history.
    temperature: A number controlling the creativity of the response. 
    max_tokens: we let the AI run until its default cutoff.'''


class GatewayResponse(BaseModel):
    content: str = Field(..., description="The text generated by the AI")
    model: str = Field(..., description="The model that actually responded")
    usage: Dict[str, int] = Field(
        default_factory=dict, 
        description="Token usage tracking: {'prompt_tokens': X, 'completion_tokens': Y}"
    )

    '''This is the promise your gateway makes to your clients. No matter how messy or deeply nested the vendor's actual JSON response is, your gateway will clean it up and return it in this flat, predictable structure.
    
    usage: A dictionary that tracks cost and consumption data (e.g., {"prompt_tokens": 12, "completion_tokens": 24}). By standardising these keys, you can build a unified analytics or billing feature later.'''