"""fix_audit_log_relationships

Revision ID: 2c1a5a4cf0d9
Revises: 8cacfc55c18e
Create Date: 2026-06-30 10:02:57.859171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1a5a4cf0d9'
down_revision: Union[str, Sequence[str], None] = '8cacfc55c18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
