"""add_non_nullable_key_id

Revision ID: 7fad9b562c4a
Revises: drop_key_prefix_001
Create Date: 2026-06-26 11:23:51.974598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad9b562c4a'
down_revision: Union[str, Sequence[str], None] = 'drop_key_prefix_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_id', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_column('api_keys', 'key_id')
    # ### end Alembic commands ###
