"""update_audit_logs_ondelete_to_set_null

Revision ID: 8cacfc55c18e
Revises: 7fad9b562c4a
Create Date: 2026-06-30 09:54:53.194607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cacfc55c18e'
down_revision: Union[str, Sequence[str], None] = '7fad9b562c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
